name: CI

on: push

jobs:
  build:
    name: "Changelog generation"
    runs-on: ubuntu-18.04
    steps:
      - name: "Check-out"
        uses: actions/checkout@v2
      - name: "Generate full changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG-G.md
      - name: "Print changelog to console"
        run: cat CHANGELOG-G.md
      - name: "Upload changelog"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Changelog"
          path: CHANGELOG-G.md